import torch
import numpy as np

config = {
    'record': False,
    'save_dir': None,
    'scene_encoder_path': './checkpoints/scene_encoder.pt',
    'pre_trained_encoder': True,
    'freeze_encoder': True,
    'save_every': 100000,
    'compile_models': False,
    # Model config
    'local_num_freq': 10,
    'local_nn_dim': 512,
    'hidden_dim': 1024,
    'num_demos': 2,
    'randomise_num_demos': False,
    'num_demos_test': 2,
    'traj_horizon': 10,
    'device': 'cuda',
    'batch_size': 16,
    'batch_size_val': 1,
    'num_scenes_nodes': 16,
    'pre_horizon': 8,
    'pos_in_nodes': True,
    'num_layers': 2,

    # Diffusion config
    'lr': 1e-5,
    'weight_decay': 1e-2,
    'use_lr_scheduler': False,
    'num_warmup_steps': 1000,
    'num_diffusion_iters_train': 100,
    'num_diffusion_iters_test': 8,
    'num_iters': 50000000001,

    'test_every': 50000,
    'randomize_g_prob': 0.1,

    'min_actions': torch.tensor([-0.01] * 3 + [-np.deg2rad(3), -np.deg2rad(3), -np.deg2rad(3)], dtype=torch.float32),
    'max_actions': torch.tensor([0.01] * 3 + [np.deg2rad(3), np.deg2rad(3), np.deg2rad(3)], dtype=torch.float32),

    # History-aware track config
    'enable_track_nodes': True,
    'track_n_max': 2,
    'track_history_len': 16,
    'track_points_per_obj': 5,
    'track_hidden_dim': 512,
    'track_patch_size': 4,
    'track_num_heads': 8,
    'track_mlp_dim': 1024,
    'track_dropout': 0.1,
    'track_num_queries': 1,
    'track_num_self_layers': 2,
    'use_light_track_encoder': False,
    'track_age_embed_dim': 32,
    'track_age_norm_max_sec': 2.0,
    'soft_membership_sigma': 0.05,
    'enable_track_track_edges': False,
    'enable_track_geo_edges': True,
    'enable_demo_current_track_edges': False,
    'enable_current_track_to_action_edges': False,
    'curriculum_dropout_start': 0.0,
    'curriculum_dropout_end': 0.0,
    'curriculum_dropout_warmup_steps': 0,
    'curriculum_dropout_hold_steps': 0,
    'track_modality_dropout_eval': 0.0,
    'track_recent_drop_prob': 0.3,
    'track_recent_drop_max_steps': 4,
    'track_recent_drop_dt_sec': 0.1,
}
